### ISSUE TITLE
Multiple call to the function returns strange results

### ISSUE THREAD

**Issue by GMartigny** [SeregPie/almete.KMeans#1]
Hi,

I ran into a weird issue while using your lib. I want to reduce the color palette of a GIF file to fit into 256 colors. It works well the first time. But when I do it twice, the function yield glitch results.

Here, you can see twice the same pixel data rendered in two separate frame on a GIF. As you might see, the first frame is ok, but the second has broken pixel values on the shape rim.

![gif test](https://i.imgur.com/o8q10bZ.gif)

Every time I tried, it does the same thing, I have the same result. Trying 3 frames, give me 1 good frame followed by 2 glitch frames.

IMO, the [`Object.assign` on line 9](https://github.com/SeregPie/KMeans/blob/master/src/index.js#L9) is to blame here. What was the point of it ?

Great lib by the way =)

**Comment by SeregPie** [comment]
Hi.
`Object.assign` just assigns default options to the function itself. I use it for [K-Means++](https://github.com/SeregPie/KMeansPlusPlus).
Can you please show me a snippet how you call the function. Do you use predefined means or a number?

**Comment by GMartigny** [comment]
Thanks for your answer.

I mess around with it yesterday and I'm not quite sure my bug comes from K-mean.

You're right, removing `Object.assign` doesn't change anything for me.

Here a simplified snippet of my code:
```js
// Long list of pixel RGB values
const decoded = [[x1, y1, z1], [x2, y2, z2], ...];
const tableMax = 9;
if (decoded.length > tableMax) {
    const reduced = KMeans(decoded, tableMax)
        .map(bucket => bucket[0]);
}
```
I have a list of 3D (R, G and B) pixel values that I want to reduce. I call `KMeans` and just keep the first of each bucket.
So here, `rawMeans` is just a number.

I'll keep you updated as I need to dig deeper into it.

**Comment by GMartigny** [comment]
So, I was indeed to blame here. Sorry for bothering you.

First, I was [off by one](https://en.wikipedia.org/wiki/Off-by-one_error) on an array up in the code.
And, selecting the first entry on the bucket allow for extreme values to be picked at random.
